name: Update Dockerfile with latest Spring Boot version

on:
  schedule:
    - cron: "0 18 * * 1" # Run the workflow every Monday at 18:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an HTTP request to get the latest release tag
      - name: Get latest Spring Boot release tag
        id: get_latest_tag
        run: |
          # Make an HTTP request and save the tag
          latest_tag=$(curl -s https://api.github.com/repos/spring-projects/spring-boot/releases/latest | jq -r '.tag_name')

          # Remove the letter 'v' from the tag
          latest_version=${latest_tag#v}

          echo "Latest tag: $latest_tag"
          echo "Version without 'v': $latest_version"

          # Set environment variable for the next steps
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      # Step 3: Update the Dockerfile with the latest version
      - name: Update Dockerfile with latest Spring Boot version
        run: |
          # Replace the version in the Dockerfile
          sed -i "s/-d bootVersion=[0-9]*\.[0-9]*\.[0-9]*/-d bootVersion=${{ env.LATEST_VERSION }}/" build/Dockerfile

      # Step 4: Check if there are changes
      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code build/Dockerfile; then
            echo "No changes detected."
            echo "CHANGED=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      # Step 5: Commit and push the changes if there are any
      - name: Commit and push changes
        if: env.CHANGED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/Dockerfile
          git commit -m "Update Dockerfile with Spring Boot version ${{ env.LATEST_VERSION }}"
          git push
