name: Update Dockerfile with latest Spring Boot version

on:
  schedule:
    - cron: "0 18 * * 1" # Run the workflow every Monday at 18:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an HTTP request to get the latest release tag
      - name: Get latest Spring Boot release tag
        id: get_latest_tag
        run: |
          # Make an HTTP request and save the tag
          latest_tag=$(curl -s https://api.github.com/repos/spring-projects/spring-boot/releases/latest | jq -r '.tag_name')

          # Remove the letter 'v' from the tag
          latest_version=${latest_tag#v}

          echo "Latest tag: $latest_tag"
          echo "Version without 'v': $latest_version"

          # Pass the version as output for the next step
          echo "::set-output name=version::$latest_version"

      # Step 3: Update the Dockerfile with the latest version
      - name: Update Dockerfile with latest Spring Boot version
        run: |
          # Replace the version in the Dockerfile
          sed -i "s/-d bootVersion=[0-9]*\.[0-9]*\.[0-9]*/-d bootVersion=${{ steps.get_latest_tag.outputs.version }}/" build/Dockerfile

      # Step 4: Commit and push the changes
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/Dockerfile
          git commit -m "Update Dockerfile with Spring Boot version ${{ steps.get_latest_tag.outputs.version }}"
          git push
